apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbnb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airbnbapp
  template:
    metadata:
      labels:
        app: airbnbapp
    spec:
      containers:
      - name: airbnbapp
        image: gcr.io/airbnb/airbnbapp
        ports:
        - containerPort: 8501